version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:20-bookworm
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks: [devnet]
    depends_on: [db]

  n8n:
    image: n8nio/n8n:1
    ports: ["5678:5678"]
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8npass
    networks: [devnet]
    depends_on: [db]

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8n
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
    networks: [devnet]

networks:
  devnet:

volumes:
  dbdata:
